<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260919103934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Likes table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD2DA06FCFE419E2 ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CD2DA06F156BE243 ON cv_like (recruiter_id)');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06FCFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06F156BE243 FOREIGN KEY (recruiter_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06FCFE419E2');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06F156BE243');
        $this->addSql('DROP TABLE cv_like');
    }
}
