<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260919072242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Position Attribute table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_order INT DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF5BEE86DD842E46 ON position_attribute (position_id)');
        $this->addSql('CREATE INDEX IDX_AF5BEE86B6E62EFA ON position_attribute (attribute_id)');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_attribute ADD CONSTRAINT FK_AF5BEE86B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute_definition (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86DD842E46');
        $this->addSql('ALTER TABLE position_attribute DROP CONSTRAINT FK_AF5BEE86B6E62EFA');
        $this->addSql('DROP TABLE position_attribute');
    }
}
