<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260918082556 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Attribute table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute_definition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, value_type VARCHAR(255) NOT NULL, bultin_key VARCHAR(255) DEFAULT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C5628BD12469DE2 ON attribute_definition (category_id)');
        $this->addSql('ALTER TABLE attribute_definition ADD CONSTRAINT FK_6C5628BD12469DE2 FOREIGN KEY (category_id) REFERENCES attribute_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_attribute_category_name RENAME TO UNIQ_9ACE83315E237E06');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_definition DROP CONSTRAINT FK_6C5628BD12469DE2');
        $this->addSql('DROP TABLE attribute_definition');
        $this->addSql('ALTER INDEX uniq_9ace83315e237e06 RENAME TO uniq_attribute_category_name');
    }
}
