<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260919073817 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Position Access Rule table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operation VARCHAR(255) NOT NULL, text_operand TEXT DEFAULT NULL, numeric_operand INT DEFAULT NULL, date_operand DATE DEFAULT NULL, period_start_operand DATE DEFAULT NULL, period_end_operand DATE DEFAULT NULL, boolen_operand BOOLEAN DEFAULT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D97A8C6DD842E46 ON position_access_rule (position_id)');
        $this->addSql('CREATE INDEX IDX_5D97A8C6B6E62EFA ON position_access_rule (attribute_id)');
        $this->addSql('CREATE INDEX IDX_5D97A8C6A7C41D6F ON position_access_rule (option_id)');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6A7C41D6F FOREIGN KEY (option_id) REFERENCES attribute_option (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6DD842E46');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6B6E62EFA');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6A7C41D6F');
        $this->addSql('DROP TABLE position_access_rule');
    }
}
