<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260919104729 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Discussion(chat) table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discussion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C0B9F90FDD842E46 ON discussion (position_id)');
        $this->addSql('CREATE INDEX IDX_C0B9F90FF675F31B ON discussion (author_id)');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90FDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FDD842E46');
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FF675F31B');
        $this->addSql('DROP TABLE discussion');
    }
}
