<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260918134712 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'User Attribute Option table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text_value TEXT DEFAULT NULL, image_reference VARCHAR(2024) DEFAULT NULL, nemeric_value INT DEFAULT NULL, date_value DATE DEFAULT NULL, period_start DATE DEFAULT NULL, period_end DATE DEFAULT NULL, boolen_value BOOLEAN DEFAULT NULL, version INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, owner_id INT NOT NULL, attribute_id INT NOT NULL, option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EC93D70D7E3C61F9 ON user_attribute_value (owner_id)');
        $this->addSql('CREATE INDEX IDX_EC93D70DB6E62EFA ON user_attribute_value (attribute_id)');
        $this->addSql('CREATE INDEX IDX_EC93D70DA7C41D6F ON user_attribute_value (option_id)');
        $this->addSql('ALTER TABLE user_attribute_value ADD CONSTRAINT FK_EC93D70D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_attribute_value ADD CONSTRAINT FK_EC93D70DB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute_definition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_attribute_value ADD CONSTRAINT FK_EC93D70DA7C41D6F FOREIGN KEY (option_id) REFERENCES attribute_option (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_attribute_value DROP CONSTRAINT FK_EC93D70D7E3C61F9');
        $this->addSql('ALTER TABLE user_attribute_value DROP CONSTRAINT FK_EC93D70DB6E62EFA');
        $this->addSql('ALTER TABLE user_attribute_value DROP CONSTRAINT FK_EC93D70DA7C41D6F');
        $this->addSql('DROP TABLE user_attribute_value');
    }
}
