<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260917103230 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'UserAuthIdentity table created';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_auth_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(255) NOT NULL, provider_subject VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0E1C3127E3C61F9 ON user_auth_identity (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AUTH_PROVIDER_SUBJECT ON user_auth_identity (provider, provider_subject)');
        $this->addSql('ALTER TABLE user_auth_identity ADD CONSTRAINT FK_A0E1C3127E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN lacale TO locale');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_auth_identity DROP CONSTRAINT FK_A0E1C3127E3C61F9');
        $this->addSql('DROP TABLE user_auth_identity');
        $this->addSql('ALTER TABLE "user" RENAME COLUMN locale TO lacale');
    }
}
